name: Build and test project


on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: install dependencies
        run: sudo apt-get -y install cmake libopencv-dev libspdlog-dev libargparse-dev
      - uses: actions/cache@v4
        with:
          path: build
          key: cmake
      - uses: actions/checkout@v4.1.1
        with:
            submodules: recursive
      - name: build
        run: cmake -B build && cmake --build build -j4
        env:
            CXX: g++-13
      - name: test
        run: ctest --test-dir build
